name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: plugin

  hassfest-lovelace:
    name: Lint hacs.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate hacs.json is valid JSON
        run: python3 -c "import json; json.load(open('hacs.json'))"
